title: Acervo Polícia RCC
description: O acervo da Polícia RCC que reune história, fatos históricos, imagens, depoimentos e muito mais em um só lugar. Saber a história é mantê-la viva.
theme: just-the-docs

url: https://acervorcc.netlify.app

logo: https://2img.net/i.imgur.com/8taLDTi.png
favicon_ico: https://2img.net/i.imgur.com/8taLDTi.ico

search_enabled: true

heading_anchors: true

footer_content: "Copyright &copy; Caiorocha1230. Polícia RCC"

color_scheme: dark

callouts:
  warning:
    title: Warning
    color: yellow
    
just_the_docs:
  custom_css:
    - assets/css/custom.css
